version: '3.8'
services:
  postgres:
    image: postgres:12.6-alpine
    env_file:
      - '.env'
    ports:
      - 25432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
  redis:
    image: redis:6.2-alpine
    env_file:
      - '.env'
    ports:
      - 26379:6379
    volumes:
      - redis-data:/data:rw
volumes:
  postgres-data:
  redis-data:
