/* eslint-disable */
/* REGENERATE THIS FILE BY RUNNING > bin/rails graphql:create_graphql_schema && yarn run graphql:updateTypes */
import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
export type Maybe<T> = T | null;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
const defaultOptions =  {}
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  /** An ISO 8601-encoded datetime */
  ISO8601DateTime: any;
  Interval: any;
};

export type Feed = {
  __typename?: 'Feed';
  createdAt: Scalars['ISO8601DateTime'];
  id: Scalars['ID'];
  lastDocument?: Maybe<Scalars['String']>;
  lastPollAt?: Maybe<Scalars['ISO8601DateTime']>;
  name: Scalars['String'];
  nextPollAt?: Maybe<Scalars['ISO8601DateTime']>;
  pollingInterval?: Maybe<Scalars['Interval']>;
  updatedAt: Scalars['ISO8601DateTime'];
  url: Scalars['String'];
};



export type Mutation = {
  __typename?: 'Mutation';
  pushoverNotification?: Maybe<PushoverNotificationPayload>;
  /** An example field added by the generator */
  testField: Scalars['String'];
};


export type MutationPushoverNotificationArgs = {
  input: PushoverNotificationInput;
};

/** Autogenerated input type of PushoverNotification */
export type PushoverNotificationInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  message: Scalars['String'];
};

/** Autogenerated return type of PushoverNotification */
export type PushoverNotificationPayload = {
  __typename?: 'PushoverNotificationPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  result: Scalars['String'];
};

export type Query = {
  __typename?: 'Query';
  /** Fetch feeds in the system */
  feeds?: Maybe<Feed>;
  /** An example field added by the generator */
  testField: Scalars['String'];
};

export type PushoverNotificationMutationVariables = Exact<{
  message: Scalars['String'];
}>;


export type PushoverNotificationMutation = (
  { __typename?: 'Mutation' }
  & { pushoverNotification?: Maybe<(
    { __typename?: 'PushoverNotificationPayload' }
    & Pick<PushoverNotificationPayload, 'result'>
  )> }
);

export type Unnamed_1_QueryVariables = Exact<{ [key: string]: never; }>;


export type Unnamed_1_Query = (
  { __typename?: 'Query' }
  & Pick<Query, 'testField'>
);


export const PushoverNotificationDocument = gql`
    mutation PushoverNotification($message: String!) {
  pushoverNotification(input: {message: $message}) {
    result
  }
}
    `;
export type PushoverNotificationMutationFn = Apollo.MutationFunction<PushoverNotificationMutation, PushoverNotificationMutationVariables>;

/**
 * __usePushoverNotificationMutation__
 *
 * To run a mutation, you first call `usePushoverNotificationMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `usePushoverNotificationMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [pushoverNotificationMutation, { data, loading, error }] = usePushoverNotificationMutation({
 *   variables: {
 *      message: // value for 'message'
 *   },
 * });
 */
export function usePushoverNotificationMutation(baseOptions?: Apollo.MutationHookOptions<PushoverNotificationMutation, PushoverNotificationMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<PushoverNotificationMutation, PushoverNotificationMutationVariables>(PushoverNotificationDocument, options);
      }
export type PushoverNotificationMutationHookResult = ReturnType<typeof usePushoverNotificationMutation>;
export type PushoverNotificationMutationResult = Apollo.MutationResult<PushoverNotificationMutation>;
export type PushoverNotificationMutationOptions = Apollo.BaseMutationOptions<PushoverNotificationMutation, PushoverNotificationMutationVariables>;
export const Document = gql`
    {
  testField
}
    `;

/**
 * __useQuery__
 *
 * To run a query within a React component, call `useQuery` and pass it any options that fit your needs.
 * When your component renders, `useQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useQuery({
 *   variables: {
 *   },
 * });
 */
export function useQuery(baseOptions?: Apollo.QueryHookOptions<Query, QueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<Query, QueryVariables>(Document, options);
      }
export function useLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<Query, QueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<Query, QueryVariables>(Document, options);
        }
export type QueryHookResult = ReturnType<typeof useQuery>;
export type LazyQueryHookResult = ReturnType<typeof useLazyQuery>;
export type QueryResult = Apollo.QueryResult<Query, QueryVariables>;

      export interface PossibleTypesResultData {
        possibleTypes: {
          [key: string]: string[]
        }
      }
      const result: PossibleTypesResultData = {
  "possibleTypes": {}
};
      export default result;
    