# This is the production overrides compose file
version: "3.8"
services:
  proxy:
    image: noosphere-proxy:latest
    command: sh -c "/wait && nginx"
    environment:
      WAIT_HOSTS: web:6040
      WAIT_BEFORE_HOSTS: 15 # Wait before checking for web to be started
      WAIT_HOSTS_TIMEOUT: 150 # Give 2.5min to run for migrations and asset compilation
      WAIT_SLEEP_INTERVAL: 10
    restart: always
    ports:
      - 6080:6080
    volumes:
      - ./config/docker/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - webassets-data:/usr/share/nginx/html:ro
  web:
    image: noosphere:latest
    # Webpack seems to need to recompile. The copy assets to the volume shared with proxy 🤝
    command: sh -c "bin/rails webpacker:compile && cp --recursive public/* /var/assets && /wait && puma -C config/puma.rb"
    environment:
      WAIT_HOSTS: redis:6379,postgres:5432
      WAIT_HOSTS_TIMEOUT: 60
    restart: always
    ports:
      - 6040:6040
    volumes:
      - log-data:/app/log
      - webassets-data:/var/assets:rw
    env_file:
      - ".env"
      - ".env.production.local"
    depends_on:
      - postgres
      - redis
  clockwork:
    image: noosphere:latest
    command: sh -c "/wait && bin/clockwork config/clockwork.rb"
    environment:
      WAIT_HOSTS: redis:6379,postgres:5432
      WAIT_HOSTS_TIMEOUT: 60
    restart: always
    volumes:
      - log-data:/app/log
    env_file:
      - ".env"
      - ".env.production.local"
    depends_on:
      - postgres
      - redis
  goodjob:
    image: noosphere:latest
    command: sh -c "/wait && bin/good_job start"
    environment:
      WAIT_HOSTS: redis:6379,postgres:5432
      WAIT_HOSTS_TIMEOUT: 60
    restart: always
    volumes:
      - log-data:/app/log
    env_file:
      - ".env"
      - ".env.production.local"
    depends_on:
      - postgres
      - redis
  postgres:
    restart: always
    env_file:
      - ".env"
      - ".env.production.local"
  redis:
    restart: always
    env_file:
      - ".env"
      - ".env.production.local"
volumes:
  postgres-data:
  redis-data:
  log-data:
  webassets-data:
